#!/bin/sh

LOGGER_TAG=v2ray-geodata-updater

log () {
  echo $@
  logger -t $LOGGER_TAG "$@"
}

# 定义代理源数组
proxies="
https://hub.gitmirror.com
https://ghfast.top
https://ghproxy.cc
https://ghps.cc
"

# 定义下载函数
download_proxy() {
    url="$1"  # 传入的原始 URL
    path="$2"  # 保存路径
    success=false

    # 遍历所有代理源
    for proxy in $proxies; do
        log "尝试通过代理源: $proxy 下载..."
        # 拼接代理后的完整 URL
        full_url="${proxy}/${url}"

        # 使用 curl 尝试下载
       if curl -L -o "$path" "$full_url"; then
            log "下载成功: $full_url"
            success=true
            break
        else
            log "下载失败: $full_url，尝试下一个代理源..."
        fi
    done

    if [ "$success" = false ]; then
        log "所有代理源均下载失败，请检查网络或代理源状态。"
        return 1
    fi
}

#GEOIP_URL=$(curl -sL https://api.github.com/repos/v2ray/geoip/releases/latest | jq -r '.assets[].browser_download_url')
GEOIP_URL="https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip.dat"

#GEOSITE_URL=$(curl -sL https://api.github.com/repos/v2ray/domain-list-community/releases/latest | jq -r '.assets[].browser_download_url')
GEOSITE_URL="https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"

GEOIP_PATH=/usr/share/v2ray/geoip.dat
GEOSITE_PATH=/usr/share/v2ray/geosite.dat

log "geoip.dat will be saved as $GEOIP_PATH"
log "geosite.dat will be saved as $GEOSITE_PATH"

log "downloading geoip.dat..."
download_proxy $GEOIP_URL /tmp/geoip.dat
if [ $? -ne 0 ]; then
  log "failed to download latest geoip.dat, not updating!"
else
  mv /tmp/geoip.dat $GEOIP_PATH
  log "v2ray geoip.dat updated"
fi

log "downloading geosite.dat..."
download_proxy $GEOSITE_URL /tmp/geosite.dat
if [ $? -ne 0 ]; then
  log "failed to download latest geosite.dat, not updating!"
else
  mv /tmp/geosite.dat $GEOSITE_PATH
  log "v2ray geosite.dat updated"
fi

#重启dead
/etc/init.d/daed running && /etc/init.d/daed restart
